const ResidenceOwner = [
  {
    relatedRode: "ResidenceOwner",
    home: "homeA",
    fields: [
      "kitchenOutletsEastKw",
      "kitchenOutletsSouthKw",
      "refrigeratorKw",
      "kitchenDenLightsKw",
      "kitchenLightsKw",
      "fridgeRangeKw",
      "furnaceHRVKw",
      "microwaveKw",
      "dishwasherDisposalSinkLightKw",
      "disposalDishwasherKw",
      "dryerKw",
      "washingMachineKw",
    ],
  },
  {
    relatedRode: "ResidenceOwner",
    home: "homeB",
    fields: [
      "furnaceKw",
      "microwaveRKw",
      "fridgeRKw",
      "microwaveKw",
      "fridgeKw",
      "washerKw",
      "dryerEgaugeKw",
      "dishwasherKw",
      "tubWhirpoolKw",
    ],
  },
  {
    relatedRode: "ResidenceOwner",
    home: "homeC",
    fields: [
      "kitchenTwelweKw",
      "kitchenFourteenKw",
      "kitchenThirtyEigthtKw",
      "microwaveKw",
      "furnaceOneKw",
      "furnaceTwoKw",
      "fridgeKw",
      "wineCellarKw",
      "dishwasherKw",
      "washerDrierKw",
      "solarKw",
    ],
  },
  {
    relatedRode: "ResidenceOwner",
    home: "homeD",
    fields: [
      "kitchenLightingKw",
      "kitchenReceptaclesKw",
      "microwaveKw",
      "refrigeratorKw",
      "kitchenIslandKw",
      "dryerKw",
      "washingMachineKw",
      "freshAirVentilationKw",
      "photovoltaicsKw",
      "housePanelKw",
    ],
  },
  {
    relatedRode: "ResidenceOwner",
    home: "homeE",
    fields: [
      "kitchenKw",
      "furnaceKw",
      "ovenKw",
      "fridgeEntLightsKw",
      "hotWaterHeaterKw",
      "dishwasherKw",
      "dryerKw",
      "clothesWashingMachineKw",
      "elecHeatKw",
    ],
  },
  {
    relatedRode: "ResidenceOwner",
    home: "homeF",
    fields: [
      "refrigeratorKw",
      "microwaveKw",
      "furnaceKw",
      "kitStoveWallKw",
      "kitSinkWallKw",
      "waterHeaterKw",
      "waterHeater3Kw",
      "waterHeater2Kw",
      "waterHeater1Kw",
      "dishwasherDisposalKw",
      "dryerKw",
      "washingMachineKw",
      "solarKw",
    ],
  },
];

const HomeOwner = [
  {
    relatedRode: "HomeOwner",
    home: "homeA",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "furnaceHRVKw",
      "cellarOutletsKw",
      "washingMachineKw",
      "fridgeRangeKw",
      "disposalDishwasherKw",
      "kitchenLightsKw",
      "bedroomOutletsKw",
      "bedroomLightsKw",
      "masterOutletsKw",
      "masterLightsKw",
      "ductHeaterHRVKw",
      "electricRangeKw",
      "dryerKw",
      "garageMudroomLightsKw",
      "diningRoomOutletsKw",
      "mudroomOutletsKw",
      "masterBathOutletsKw",
      "garageOutletsKw",
      "basementOutdoorOutletsKw",
      "kitchenDenLightsKw",
      "masterBedBathLightsKw",
      "masterOutletsKw",
      "denOutdoorLightsKw",
      "denOutletsKw",
      "rearBasementLightsKw",
      "kitchenOutletsEastKw",
      "kitchenOutletsSouthKw",
      "dishwasherDisposalSinkLightKw",
      "refrigeratorKw",
      "microwaveKw",
      "officeLightsKw",
    ],
  },
  {
    relatedRode: "HomeOwner",
    home: "homeB",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "gridKw",
      "ACKw",
      "furnaceKw",
      "cellarLightsKw",
      "washerKw",
      "firstFloorLightsKw",
      "utilityRmBasementBathKw",
      "garageOutletsKw",
      "mBedKBedOutletsKw",
      "dryerEgaugeKw",
      "panelGFICentralKw",
      "homeOfficeRKw",
      "diningRoomRKw",
      "microwaveRKw",
      "fridgeRKw",
      "oldUsageKw",
      "homeOfficeKw",
      "diningRoomKw",
      "microwaveKw",
      "firstFloorKw",
      "tubWhirpoolKw",
      "kitchenCounterKw",
      "dishwasherKw",
      "fridgeKw",
      "guestBedroomMediaRoomKw",
      "mBedKBedLightsMasterBathkw",
      "livingRoomKitchenLightsKw",
      "bathGFIKw",
    ],
  },
  {
    relatedRode: "HomeOwner",
    home: "homeC",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "houseOverallKw",
      "dishwasherKw",
      "furnaceOneKw",
      "furnaceTwoKw",
      "homeOfficeKw",
      "fridgeKw",
      "wineCellarKw",
      "garageDoorKw",
      "kitchenTwelweKw",
      "kitchenFourteenKw",
      "kitchenThirtyEigthtKw",
      "barnKw",
      "wellKw",
      "microwaveKw",
      "livingRoomKw",
      "solarKw",
      "livingRoomOutletsKw",
      "washerDrierKw",
    ],
  },
  {
    relatedRode: "HomeOwner",
    home: "homeD",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "freshAirVentilationKw",
      "housePanelKw",
      "livingRoomReceptaclesKw",
      "secondFloorBathroomKw",
      "washingMachineKw",
      "studiesOutsideLightingKw",
      "diningRoomReceptaclesKw",
      "basementHallLightingKw",
      "guestHouseBathroomKw",
      "guestHouseBedroomKw",
      "workshopReceptacleBathHeaterKw",
      "guestHouseKitchenKw",
      "groundSourceHeatPumpKw",
      "photovoltaicsKw",
      "wellPumpKw",
      "rangeKw",
      "panelReceptaclesKw",
      "kitchenReceptaclesKw",
      "microwaveKw",
      "refrigeratorKw",
      "netHousePowerUsageKw",
      "garageReceptaclesLightsKw",
      "garageReceptaclesKw",
      "shedReceptaclesKw",
      "shedLightsKw",
      "garagePVKw",
      "guestHouseLivingRoomKw",
      "masterBedroomKw",
      "heatCirculatorPumpsKw",
      "domesticHotWaterReserveKw",
      "masterBathroomKw",
      "kitchenIslandKw",
      "radiantHeatReserveTankKw",
      "basementReceptaclesKw",
      "dryerKw",
      "kitchenLightingKw",
      "guestHouseDiningRoomReceptKw",
      "porchVerandaLightingKw",
    ],
  },
  {
    relatedRode: "HomeOwner",
    home: "homeE",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "kitchenOutletEspressoKw",
      "hotWaterHeaterKw",
      "diningRoomKw",
      "fridgeEntLightsKw",
      "clothesWashingMachineKw",
      "dishwasherKw",
      "secondFloorBedroomKw",
      "masterNEbedroomBathKw",
      "elecHeatKw",
      "furnaceKw",
      "laundLivingRHallLightsKw",
      "gridKw",
      "kitchenKw",
      "firstFloorBedroomKw",
      "ovenKw",
      "dryerKw",
      "basementDehumidifierKw",
      "basementFamilyRoomKw",
      "elecHeatBedWBathNKw",
    ],
  },
  {
    relatedRode: "HomeOwner",
    home: "homeF",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "waterHeaterKw",
      "solarKw",
      "refrigeratorKw",
      "microwaveKw",
      "furnaceKw",
      "waterHeater3Kw",
      "waterHeater2Kw",
      "waterHeater1Kw",
      "masterBdrmKw",
      "frontBdrmKw",
      "kitStoveWallKw",
      "dishwasherDisposalKw",
      "kitSinkWallKw",
      "familyRmKw",
      "kitHalfBathFoyerKw",
      "washingMachineKw",
      "guestBdrmSmkDetKw",
      "dryerKw",
      "basementKw",
      "phaseBKw",
      "phaseAKw",
      "netMeterKw",
      "voltKw",
      "garageEKw",
      "garageWKw",
    ],
  },
];

const UnderageResident = [
  {
    relatedRode: "UnderageResident",
    home: "homeA",
    fields: [
      "dateTime",
      "washingMachineKw",
      "fridgeRangeKw",
      "kitchenLightsKw",
      "bedroomLightsKw",
      "dryerKw",
      "garageMudroomLightsKw",
      "kitchenDenLightsKw",
      "masterBedBathLightsKw",
      "denOutdoorLightsKw",
      "rearBasementLightsKw",
      "kitchenOutletsEastKw",
      "refrigeratorKw",
      "microwaveKw",
      "officeLightsKw",
    ],
  },
  {
    relatedRode: "UnderageResident",
    home: "homeB",
    fields: [
      "dateTime",
      "washerKw",
      "firstFloorLightsKw",
      "dryerEgaugeKw",
      "diningRoomRKw",
      "microwaveRKw",
      "fridgeRKw",
      "diningRoomKw",
      "microwaveKw",
      "tubWhirpoolKw",
      "dishwasherKw",
      "fridgeKw",
      "mBedKBedLightsMasterBathkw",
      "livingRoomKitchenLightsKw",
    ],
  },
  {
    relatedRode: "UnderageResident",
    home: "homeC",
    fields: [
      "dateTime",
      "dishwasherKw",
      "fridgeKw",
      "barnKw",
      "wellKw",
      "microwaveKw",
      "livingRoomKw",
      "washerDrierKw",
    ],
  },
  {
    relatedRode: "UnderageResident",
    home: "homeD",
    fields: [
      "dateTime",
      "freshAirVentilationKw",
      "secondFloorBathroomKw",
      "washingMachineKw",
      "diningRoomReceptaclesKw",
      "basementHallLightingKw",
      "guestHouseBathroomKw",
      "guestHouseBedroomKw",
      "workshopReceptacleBathHeaterKw",
      "guestHouseKitchenKw",
      "microwaveKw",
      "refrigeratorKw",
      "guestHouseLivingRoomKw",
      "masterBedroomKw",
      "masterBathroomKw",
      "kitchenIslandKw",
      "basementReceptaclesKw",
      "dryerKw",
      "kitchenLightingKw",
      "guestHouseDiningRoomReceptKw",
    ],
  },
  {
    relatedRode: "UnderageResident",
    home: "homeE",
    fields: [
      "dateTime",
      "kitchenOutletEspressoKw",
      "diningRoomKw",
      "fridgeEntLightsKw",
      "clothesWashingMachineKw",
      "dishwasherKw",
      "secondFloorBedroomKw",
      "laundLivingRHallLightsKw",
      "kitchenKw",
      "firstFloorBedroomKw",
      "ovenKw",
      "dryerKw",
      "basementFamilyRoomKw",
    ],
  },
  {
    relatedRode: "UnderageResident",
    home: "homeF",
    fields: [
      "dateTime",
      "refrigeratorKw",
      "microwaveKw",
      "masterBdrmKw",
      "frontBdrmKw",
      "kitStoveWallKw",
      "dishwasherDisposalKw",
      "kitSinkWallKw",
      "familyRmKw",
      "kitHalfBathFoyerKw",
      "washingMachineKw",
      "guestBdrmSmkDetKw",
      "dryerKw",
      "basementKw",
    ],
  },
];

const Tenant = [
  {
    relatedRode: "Tenant",
    home: "homeA",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "furnaceHRVKw",
      "cellarOutletsKw",
      "washingMachineKw",
      "fridgeRangeKw",
      "disposalDishwasherKw",
      "kitchenLightsKw",
      "bedroomOutletsKw",
      "bedroomLightsKw",
      "masterOutletsKw",
      "masterLightsKw",
      "ductHeaterHRVKw",
      "electricRangeKw",
      "dryerKw",
      "garageMudroomLightsKw",
      "diningRoomOutletsKw",
      "mudroomOutletsKw",
      "masterBathOutletsKw",
      "garageOutletsKw",
      "basementOutdoorOutletsKw",
      "kitchenDenLightsKw",
      "masterBedBathLightsKw",
      "masterOutletsKw",
      "denOutdoorLightsKw",
      "denOutletsKw",
      "rearBasementLightsKw",
      "kitchenOutletsEastKw",
      "kitchenOutletsSouthKw",
      "dishwasherDisposalSinkLightKw",
      "refrigeratorKw",
      "microwaveKw",
      "officeLightsKw",
    ],
  },
  {
    relatedRode: "Tenant",
    home: "homeB",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "gridKw",
      "ACKw",
      "furnaceKw",
      "cellarLightsKw",
      "washerKw",
      "firstFloorLightsKw",
      "utilityRmBasementBathKw",
      "garageOutletsKw",
      "mBedKBedOutletsKw",
      "dryerEgaugeKw",
      "panelGFICentralKw",
      "homeOfficeRKw",
      "diningRoomRKw",
      "microwaveRKw",
      "fridgeRKw",
      "oldUsageKw",
      "homeOfficeKw",
      "diningRoomKw",
      "microwaveKw",
      "firstFloorKw",
      "tubWhirpoolKw",
      "kitchenCounterKw",
      "dishwasherKw",
      "fridgeKw",
      "guestBedroomMediaRoomKw",
      "mBedKBedLightsMasterBathkw",
      "livingRoomKitchenLightsKw",
      "bathGFIKw",
    ],
  },
  {
    relatedRode: "Tenant",
    home: "homeC",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "houseOverallKw",
      "dishwasherKw",
      "furnaceOneKw",
      "furnaceTwoKw",
      "homeOfficeKw",
      "fridgeKw",
      "wineCellarKw",
      "garageDoorKw",
      "kitchenTwelweKw",
      "kitchenFourteenKw",
      "kitchenThirtyEigthtKw",
      "barnKw",
      "wellKw",
      "microwaveKw",
      "livingRoomKw",
      "solarKw",
      "livingRoomOutletsKw",
      "washerDrierKw",
    ],
  },
  {
    relatedRode: "Tenant",
    home: "homeD",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "freshAirVentilationKw",
      "housePanelKw",
      "livingRoomReceptaclesKw",
      "secondFloorBathroomKw",
      "washingMachineKw",
      "studiesOutsideLightingKw",
      "diningRoomReceptaclesKw",
      "basementHallLightingKw",
      "guestHouseBathroomKw",
      "guestHouseBedroomKw",
      "workshopReceptacleBathHeaterKw",
      "guestHouseKitchenKw",
      "groundSourceHeatPumpKw",
      "photovoltaicsKw",
      "wellPumpKw",
      "rangeKw",
      "panelReceptaclesKw",
      "kitchenReceptaclesKw",
      "microwaveKw",
      "refrigeratorKw",
      "netHousePowerUsageKw",
      "garageReceptaclesLightsKw",
      "garageReceptaclesKw",
      "shedReceptaclesKw",
      "shedLightsKw",
      "garagePVKw",
      "guestHouseLivingRoomKw",
      "masterBedroomKw",
      "heatCirculatorPumpsKw",
      "domesticHotWaterReserveKw",
      "masterBathroomKw",
      "kitchenIslandKw",
      "radiantHeatReserveTankKw",
      "basementReceptaclesKw",
      "dryerKw",
      "kitchenLightingKw",
      "guestHouseDiningRoomReceptKw",
      "porchVerandaLightingKw",
    ],
  },
  {
    relatedRode: "Tenant",
    home: "homeE",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "kitchenOutletEspressoKw",
      "hotWaterHeaterKw",
      "diningRoomKw",
      "fridgeEntLightsKw",
      "clothesWashingMachineKw",
      "dishwasherKw",
      "secondFloorBedroomKw",
      "masterNEbedroomBathKw",
      "elecHeatKw",
      "furnaceKw",
      "laundLivingRHallLightsKw",
      "gridKw",
      "kitchenKw",
      "firstFloorBedroomKw",
      "ovenKw",
      "dryerKw",
      "basementDehumidifierKw",
      "basementFamilyRoomKw",
      "elecHeatBedWBathNKw",
    ],
  },
  {
    relatedRode: "Tenant",
    home: "homeF",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "waterHeaterKw",
      "solarKw",
      "refrigeratorKw",
      "microwaveKw",
      "furnaceKw",
      "waterHeater3Kw",
      "waterHeater2Kw",
      "waterHeater1Kw",
      "masterBdrmKw",
      "frontBdrmKw",
      "kitStoveWallKw",
      "dishwasherDisposalKw",
      "kitSinkWallKw",
      "familyRmKw",
      "kitHalfBathFoyerKw",
      "washingMachineKw",
      "guestBdrmSmkDetKw",
      "dryerKw",
      "basementKw",
      "phaseBKw",
      "phaseAKw",
      "netMeterKw",
      "voltKw",
      "garageEKw",
      "garageWKw",
    ],
  },
];

const CleaningCompanyEmployee = [
  {
    relatedRode: "CleaningCompanyEmployee",
    home: "homeA",
    fields: [
      "dateTime",
      "cellarOutletsKw",
      "washingMachineKw",
      "disposalDishwasherKw",
      "kitchenLightsKw",
      "bedroomLightsKw",
      "masterLightsKw",
      "dryerKw",
      "kitchenDenLightsKw",
      "masterBedBathLightsKw",
      "denOutdoorLightsKw",
      "rearBasementLightsKw",
      "dishwasherDisposalSinkLightKw",
      "officeLightsKw",
    ],
  },
  {
    relatedRode: "CleaningCompanyEmployee",
    home: "homeB",
    fields: [
      "dateTime",
      "cellarLightsKw",
      "washerKw",
      "firstFloorLightsKw",
      "dryerEgaugeKw",
      "tubWhirpoolKw",
      "dishwasherKw",
      "fridgeKw",
      "guestBedroomMediaRoomKw",
      "mBedKBedLightsMasterBathkw",
      "livingRoomKitchenLightsKw",
    ],
  },
  {
    relatedRode: "CleaningCompanyEmployee",
    home: "homeC",
    fields: [
      "dateTime",
      "dishwasherKw",
      "homeOfficeKw",
      "livingRoomKw",
      "washerDrierKw",
    ],
  },
  {
    relatedRode: "CleaningCompanyEmployee",
    home: "homeD",
    fields: [
      "dateTime",
      "secondFloorBathroomKw",
      "washingMachineKw",
      "basementHallLightingKw",
      "guestHouseBathroomKw",
      "guestHouseBedroomKw",
      "guestHouseKitchenKw",
      "shedLightsKw",
      "guestHouseLivingRoomKw",
      "masterBedroomKw",
      "masterBathroomKw",
      "kitchenIslandKw",
      "dryerKw",
      "kitchenLightingKw",
    ],
  },
  {
    relatedRode: "CleaningCompanyEmployee",
    home: "homeE",
    fields: [
      "dateTime",
      "diningRoomKw",
      "fridgeEntLightsKw",
      "clothesWashingMachineKw",
      "dishwasherKw",
      "secondFloorBedroomKw",
      "masterNEbedroomBathKw",
      "laundLivingRHallLightsKw",
      "kitchenKw",
      "firstFloorBedroomKw",
      "dryerKw",
      "basementFamilyRoomKw",
    ],
  },
  {
    relatedRode: "CleaningCompanyEmployee",
    home: "homeF",
    fields: [
      "dateTime",
      "masterBdrmKw",
      "frontBdrmKw",
      "dishwasherDisposalKw",
      "kitHalfBathFoyerKw",
      "washingMachineKw",
      "guestBdrmSmkDetKw",
      "dryerKw",
      "basementKw",
    ],
  },
];

const adaptedHeader = {
  homeA: [
    "dateTime",
    "usedKw",
    "generateKw",
    "furnaceHRVKw",
    "cellarOutletsKw",
    "washingMachineKw",
    "fridgeRangeKw",
    "disposalDishwasherKw",
    "kitchenLightsKw",
    "bedroomOutletsKw",
    "bedroomLightsKw",
    "masterOutletsKw",
    "masterLightsKw",
    "ductHeaterHRVKw",
    "electricRangeKw",
    "dryerKw",
    "garageMudroomLightsKw",
    "diningRoomOutletsKw",
    "mudroomOutletsKw",
    "masterBathOutletsKw",
    "garageOutletsKw",
    "basementOutdoorOutletsKw",
    "kitchenDenLightsKw",
    "masterBedBathLightsKw",
    "masterOutletsKw",
    "denOutdoorLightsKw",
    "denOutletsKw",
    "rearBasementLightsKw",
    "kitchenOutletsEastKw",
    "kitchenOutletsSouthKw",
    "dishwasherDisposalSinkLightKw",
    "refrigeratorKw",
    "microwaveKw",
    "officeLightsKw",
  ],
  homeB: [
    "dateTime",
    "usedKw",
    "generateKw",
    "gridKw",
    "ACKw",
    "furnaceKw",
    "cellarLightsKw",
    "washerKw",
    "firstFloorLightsKw",
    "utilityRmBasementBathKw",
    "garageOutletsKw",
    "mBedKBedOutletsKw",
    "dryerEgaugeKw",
    "panelGFICentralKw",
    "homeOfficeRKw",
    "diningRoomRKw",
    "microwaveRKw",
    "fridgeRKw",
    "oldUsageKw",
    "homeOfficeKw",
    "diningRoomKw",
    "microwaveKw",
    "firstFloorKw",
    "tubWhirpoolKw",
    "kitchenCounterKw",
    "dishwasherKw",
    "fridgeKw",
    "guestBedroomMediaRoomKw",
    "mBedKBedLightsMasterBathkw",
    "livingRoomKitchenLightsKw",
    "bathGFIKw",
  ],
  homeC: [
    "dateTime",
    "usedKw",
    "generateKw",
    "houseOverallKw",
    "dishwasherKw",
    "furnaceOneKw",
    "furnaceTwoKw",
    "homeOfficeKw",
    "fridgeKw",
    "wineCellarKw",
    "garageDoorKw",
    "kitchenTwelweKw",
    "kitchenFourteenKw",
    "kitchenThirtyEigthtKw",
    "barnKw",
    "wellKw",
    "microwaveKw",
    "livingRoomKw",
    "solarKw",
    "livingRoomOutletsKw",
    "washerDrierKw",
  ],
  homeD: [
    "dateTime",
    "usedKw",
    "generateKw",
    "freshAirVentilationKw",
    "housePanelKw",
    "livingRoomReceptaclesKw",
    "secondFloorBathroomKw",
    "washingMachineKw",
    "studiesOutsideLightingKw",
    "diningRoomReceptaclesKw",
    "basementHallLightingKw",
    "guestHouseBathroomKw",
    "guestHouseBedroomKw",
    "workshopReceptacleBathHeaterKw",
    "guestHouseKitchenKw",
    "groundSourceHeatPumpKw",
    "photovoltaicsKw",
    "wellPumpKw",
    "rangeKw",
    "panelReceptaclesKw",
    "kitchenReceptaclesKw",
    "microwaveKw",
    "refrigeratorKw",
    "netHousePowerUsageKw",
    "garageReceptaclesLightsKw",
    "garageReceptaclesKw",
    "shedReceptaclesKw",
    "shedLightsKw",
    "garagePVKw",
    "guestHouseLivingRoomKw",
    "masterBedroomKw",
    "heatCirculatorPumpsKw",
    "domesticHotWaterReserveKw",
    "masterBathroomKw",
    "kitchenIslandKw",
    "radiantHeatReserveTankKw",
    "basementReceptaclesKw",
    "dryerKw",
    "kitchenLightingKw",
    "guestHouseDiningRoomReceptKw",
    "porchVerandaLightingKw",
  ],
  homeE: [
    "dateTime",
    "usedKw",
    "generateKw",
    "kitchenOutletEspressoKw",
    "hotWaterHeaterKw",
    "diningRoomKw",
    "fridgeEntLightsKw",
    "clothesWashingMachineKw",
    "dishwasherKw",
    "secondFloorBedroomKw",
    "masterNEbedroomBathKw",
    "elecHeatKw",
    "furnaceKw",
    "laundLivingRHallLightsKw",
    "gridKw",
    "kitchenKw",
    "firstFloorBedroomKw",
    "ovenKw",
    "dryerKw",
    "basementDehumidifierKw",
    "basementFamilyRoomKw",
    "elecHeatBedWBathNKw",
  ],
  homeF: [
    "dateTime",
    "usedKw",
    "generateKw",
    "waterHeaterKw",
    "solarKw",
    "refrigeratorKw",
    "microwaveKw",
    "furnaceKw",
    "waterHeater3Kw",
    "waterHeater2Kw",
    "waterHeater1Kw",
    "masterBdrmKw",
    "frontBdrmKw",
    "kitStoveWallKw",
    "dishwasherDisposalKw",
    "kitSinkWallKw",
    "familyRmKw",
    "kitHalfBathFoyerKw",
    "washingMachineKw",
    "guestBdrmSmkDetKw",
    "dryerKw",
    "basementKw",
    "phaseBKw",
    "phaseAKw",
    "netMeterKw",
    "voltKw",
    "garageEKw",
    "garageWKw",
  ],
};
