const ResidenceOwner = [
  {
    relatedRole: "ResidenceOwner",
    home: "homeA",
    fields: [
      "kitchenOutletsEastKw",
      "kitchenOutletsSouthKw",
      "refrigeratorKw",
      "kitchenDenLightsKw",
      "kitchenLightsKw",
      "fridgeRangeKw",
      "furnaceHRVKw",
      "microwaveKw",
      "dishwasherDisposalSinkLightKw",
      "disposalDishwasherKw",
      "dryerKw",
      "washingMachineKw",
    ],
  },
  {
    relatedRole: "ResidenceOwner",
    home: "homeB",
    fields: [
      "furnaceKw",
      "microwaveRKw",
      "fridgeRKw",
      "microwaveKw",
      "fridgeKw",
      "washerKw",
      "dryerEgaugeKw",
      "dishwasherKw",
      "tubWhirpoolKw",
    ],
  },
  {
    relatedRole: "ResidenceOwner",
    home: "homeC",
    fields: [
      "kitchenTwelweKw",
      "kitchenFourteenKw",
      "kitchenThirtyEigthtKw",
      "microwaveKw",
      "furnaceOneKw",
      "furnaceTwoKw",
      "fridgeKw",
      "wineCellarKw",
      "dishwasherKw",
      "washerDrierKw",
      "solarKw",
    ],
  },
  {
    relatedRole: "ResidenceOwner",
    home: "homeD",
    fields: [
      "kitchenLightingKw",
      "kitchenReceptaclesKw",
      "microwaveKw",
      "refrigeratorKw",
      "kitchenIslandKw",
      "dryerKw",
      "washingMachineKw",
      "freshAirVentilationKw",
      "photovoltaicsKw",
      "housePanelKw",
    ],
  },
  {
    relatedRole: "ResidenceOwner",
    home: "homeE",
    fields: [
      "kitchenKw",
      "furnaceKw",
      "ovenKw",
      "fridgeEntLightsKw",
      "hotWaterHeaterKw",
      "dishwasherKw",
      "dryerKw",
      "clothesWashingMachineKw",
      "elecHeatKw",
    ],
  },
  {
    relatedRole: "ResidenceOwner",
    home: "homeF",
    fields: [
      "refrigeratorKw",
      "microwaveKw",
      "furnaceKw",
      "kitStoveWallKw",
      "kitSinkWallKw",
      "waterHeaterKw",
      "waterHeater3Kw",
      "waterHeater2Kw",
      "waterHeater1Kw",
      "dishwasherDisposalKw",
      "dryerKw",
      "washingMachineKw",
      "solarKw",
    ],
  },
];

const HomeOwner = [
  {
    relatedRole: "HomeOwner",
    home: "homeA",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "furnaceHRVKw",
      "cellarOutletsKw",
      "washingMachineKw",
      "fridgeRangeKw",
      "disposalDishwasherKw",
      "kitchenLightsKw",
      "bedroomOutletsKw",
      "bedroomLightsKw",
      "masterOutletsKw",
      "masterLightsKw",
      "ductHeaterHRVKw",
      "electricRangeKw",
      "dryerKw",
      "garageMudroomLightsKw",
      "diningRoomOutletsKw",
      "mudroomOutletsKw",
      "masterBathOutletsKw",
      "garageOutletsKw",
      "basementOutdoorOutletsKw",
      "kitchenDenLightsKw",
      "masterBedBathLightsKw",
      "masterOutletsKw",
      "denOutdoorLightsKw",
      "denOutletsKw",
      "rearBasementLightsKw",
      "kitchenOutletsEastKw",
      "kitchenOutletsSouthKw",
      "dishwasherDisposalSinkLightKw",
      "refrigeratorKw",
      "microwaveKw",
      "officeLightsKw",
    ],
  },
  {
    relatedRole: "HomeOwner",
    home: "homeB",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "gridKw",
      "ACKw",
      "furnaceKw",
      "cellarLightsKw",
      "washerKw",
      "firstFloorLightsKw",
      "utilityRmBasementBathKw",
      "garageOutletsKw",
      "mBedKBedOutletsKw",
      "dryerEgaugeKw",
      "panelGFICentralKw",
      "homeOfficeRKw",
      "diningRoomRKw",
      "microwaveRKw",
      "fridgeRKw",
      "oldUsageKw",
      "homeOfficeKw",
      "diningRoomKw",
      "microwaveKw",
      "firstFloorKw",
      "tubWhirpoolKw",
      "kitchenCounterKw",
      "dishwasherKw",
      "fridgeKw",
      "guestBedroomMediaRoomKw",
      "mBedKBedLightsMasterBathkw",
      "livingRoomKitchenLightsKw",
      "bathGFIKw",
    ],
  },
  {
    relatedRole: "HomeOwner",
    home: "homeC",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "houseOverallKw",
      "dishwasherKw",
      "furnaceOneKw",
      "furnaceTwoKw",
      "homeOfficeKw",
      "fridgeKw",
      "wineCellarKw",
      "garageDoorKw",
      "kitchenTwelweKw",
      "kitchenFourteenKw",
      "kitchenThirtyEigthtKw",
      "barnKw",
      "wellKw",
      "microwaveKw",
      "livingRoomKw",
      "solarKw",
      "livingRoomOutletsKw",
      "washerDrierKw",
    ],
  },
  {
    relatedRole: "HomeOwner",
    home: "homeD",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "freshAirVentilationKw",
      "housePanelKw",
      "livingRoomReceptaclesKw",
      "secondFloorBathroomKw",
      "washingMachineKw",
      "studiesOutsideLightingKw",
      "diningRoomReceptaclesKw",
      "basementHallLightingKw",
      "guestHouseBathroomKw",
      "guestHouseBedroomKw",
      "workshopReceptacleBathHeaterKw",
      "guestHouseKitchenKw",
      "groundSourceHeatPumpKw",
      "photovoltaicsKw",
      "wellPumpKw",
      "rangeKw",
      "panelReceptaclesKw",
      "kitchenReceptaclesKw",
      "microwaveKw",
      "refrigeratorKw",
      "netHousePowerUsageKw",
      "garageReceptaclesLightsKw",
      "garageReceptaclesKw",
      "shedReceptaclesKw",
      "shedLightsKw",
      "garagePVKw",
      "guestHouseLivingRoomKw",
      "masterBedroomKw",
      "heatCirculatorPumpsKw",
      "domesticHotWaterReserveKw",
      "masterBathroomKw",
      "kitchenIslandKw",
      "radiantHeatReserveTankKw",
      "basementReceptaclesKw",
      "dryerKw",
      "kitchenLightingKw",
      "guestHouseDiningRoomReceptKw",
      "porchVerandaLightingKw",
    ],
  },
  {
    relatedRole: "HomeOwner",
    home: "homeE",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "kitchenOutletEspressoKw",
      "hotWaterHeaterKw",
      "diningRoomKw",
      "fridgeEntLightsKw",
      "clothesWashingMachineKw",
      "dishwasherKw",
      "secondFloorBedroomKw",
      "masterNEbedroomBathKw",
      "elecHeatKw",
      "furnaceKw",
      "laundLivingRHallLightsKw",
      "gridKw",
      "kitchenKw",
      "firstFloorBedroomKw",
      "ovenKw",
      "dryerKw",
      "basementDehumidifierKw",
      "basementFamilyRoomKw",
      "elecHeatBedWBathNKw",
    ],
  },
  {
    relatedRole: "HomeOwner",
    home: "homeF",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "waterHeaterKw",
      "solarKw",
      "refrigeratorKw",
      "microwaveKw",
      "furnaceKw",
      "waterHeater3Kw",
      "waterHeater2Kw",
      "waterHeater1Kw",
      "masterBdrmKw",
      "frontBdrmKw",
      "kitStoveWallKw",
      "dishwasherDisposalKw",
      "kitSinkWallKw",
      "familyRmKw",
      "kitHalfBathFoyerKw",
      "washingMachineKw",
      "guestBdrmSmkDetKw",
      "dryerKw",
      "basementKw",
      "phaseBKw",
      "phaseAKw",
      "netMeterKw",
      "voltKw",
      "garageEKw",
      "garageWKw",
    ],
  },
];

const UnderageResident = [
  {
    relatedRole: "UnderageResident",
    home: "homeA",
    fields: [
      "dateTime",
      "washingMachineKw",
      "fridgeRangeKw",
      "kitchenLightsKw",
      "bedroomLightsKw",
      "dryerKw",
      "garageMudroomLightsKw",
      "kitchenDenLightsKw",
      "masterBedBathLightsKw",
      "denOutdoorLightsKw",
      "rearBasementLightsKw",
      "kitchenOutletsEastKw",
      "refrigeratorKw",
      "microwaveKw",
      "officeLightsKw",
    ],
  },
  {
    relatedRole: "UnderageResident",
    home: "homeB",
    fields: [
      "dateTime",
      "washerKw",
      "firstFloorLightsKw",
      "dryerEgaugeKw",
      "diningRoomRKw",
      "microwaveRKw",
      "fridgeRKw",
      "diningRoomKw",
      "microwaveKw",
      "tubWhirpoolKw",
      "dishwasherKw",
      "fridgeKw",
      "mBedKBedLightsMasterBathkw",
      "livingRoomKitchenLightsKw",
    ],
  },
  {
    relatedRole: "UnderageResident",
    home: "homeC",
    fields: [
      "dateTime",
      "dishwasherKw",
      "fridgeKw",
      "barnKw",
      "wellKw",
      "microwaveKw",
      "livingRoomKw",
      "washerDrierKw",
    ],
  },
  {
    relatedRole: "UnderageResident",
    home: "homeD",
    fields: [
      "dateTime",
      "freshAirVentilationKw",
      "secondFloorBathroomKw",
      "washingMachineKw",
      "diningRoomReceptaclesKw",
      "basementHallLightingKw",
      "guestHouseBathroomKw",
      "guestHouseBedroomKw",
      "workshopReceptacleBathHeaterKw",
      "guestHouseKitchenKw",
      "microwaveKw",
      "refrigeratorKw",
      "guestHouseLivingRoomKw",
      "masterBedroomKw",
      "masterBathroomKw",
      "kitchenIslandKw",
      "basementReceptaclesKw",
      "dryerKw",
      "kitchenLightingKw",
      "guestHouseDiningRoomReceptKw",
    ],
  },
  {
    relatedRole: "UnderageResident",
    home: "homeE",
    fields: [
      "dateTime",
      "kitchenOutletEspressoKw",
      "diningRoomKw",
      "fridgeEntLightsKw",
      "clothesWashingMachineKw",
      "dishwasherKw",
      "secondFloorBedroomKw",
      "laundLivingRHallLightsKw",
      "kitchenKw",
      "firstFloorBedroomKw",
      "ovenKw",
      "dryerKw",
      "basementFamilyRoomKw",
    ],
  },
  {
    relatedRole: "UnderageResident",
    home: "homeF",
    fields: [
      "dateTime",
      "refrigeratorKw",
      "microwaveKw",
      "masterBdrmKw",
      "frontBdrmKw",
      "kitStoveWallKw",
      "dishwasherDisposalKw",
      "kitSinkWallKw",
      "familyRmKw",
      "kitHalfBathFoyerKw",
      "washingMachineKw",
      "guestBdrmSmkDetKw",
      "dryerKw",
      "basementKw",
    ],
  },
];

const Tenant = [
  {
    relatedRole: "Tenant",
    home: "homeA",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "furnaceHRVKw",
      "cellarOutletsKw",
      "washingMachineKw",
      "fridgeRangeKw",
      "disposalDishwasherKw",
      "kitchenLightsKw",
      "bedroomOutletsKw",
      "bedroomLightsKw",
      "masterOutletsKw",
      "masterLightsKw",
      "ductHeaterHRVKw",
      "electricRangeKw",
      "dryerKw",
      "garageMudroomLightsKw",
      "diningRoomOutletsKw",
      "mudroomOutletsKw",
      "masterBathOutletsKw",
      "garageOutletsKw",
      "basementOutdoorOutletsKw",
      "kitchenDenLightsKw",
      "masterBedBathLightsKw",
      "masterOutletsKw",
      "denOutdoorLightsKw",
      "denOutletsKw",
      "rearBasementLightsKw",
      "kitchenOutletsEastKw",
      "kitchenOutletsSouthKw",
      "dishwasherDisposalSinkLightKw",
      "refrigeratorKw",
      "microwaveKw",
      "officeLightsKw",
    ],
  },
  {
    relatedRole: "Tenant",
    home: "homeB",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "gridKw",
      "ACKw",
      "furnaceKw",
      "cellarLightsKw",
      "washerKw",
      "firstFloorLightsKw",
      "utilityRmBasementBathKw",
      "garageOutletsKw",
      "mBedKBedOutletsKw",
      "dryerEgaugeKw",
      "panelGFICentralKw",
      "homeOfficeRKw",
      "diningRoomRKw",
      "microwaveRKw",
      "fridgeRKw",
      "oldUsageKw",
      "homeOfficeKw",
      "diningRoomKw",
      "microwaveKw",
      "firstFloorKw",
      "tubWhirpoolKw",
      "kitchenCounterKw",
      "dishwasherKw",
      "fridgeKw",
      "guestBedroomMediaRoomKw",
      "mBedKBedLightsMasterBathkw",
      "livingRoomKitchenLightsKw",
      "bathGFIKw",
    ],
  },
  {
    relatedRole: "Tenant",
    home: "homeC",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "houseOverallKw",
      "dishwasherKw",
      "furnaceOneKw",
      "furnaceTwoKw",
      "homeOfficeKw",
      "fridgeKw",
      "wineCellarKw",
      "garageDoorKw",
      "kitchenTwelweKw",
      "kitchenFourteenKw",
      "kitchenThirtyEigthtKw",
      "barnKw",
      "wellKw",
      "microwaveKw",
      "livingRoomKw",
      "solarKw",
      "livingRoomOutletsKw",
      "washerDrierKw",
    ],
  },
  {
    relatedRole: "Tenant",
    home: "homeD",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "freshAirVentilationKw",
      "housePanelKw",
      "livingRoomReceptaclesKw",
      "secondFloorBathroomKw",
      "washingMachineKw",
      "studiesOutsideLightingKw",
      "diningRoomReceptaclesKw",
      "basementHallLightingKw",
      "guestHouseBathroomKw",
      "guestHouseBedroomKw",
      "workshopReceptacleBathHeaterKw",
      "guestHouseKitchenKw",
      "groundSourceHeatPumpKw",
      "photovoltaicsKw",
      "wellPumpKw",
      "rangeKw",
      "panelReceptaclesKw",
      "kitchenReceptaclesKw",
      "microwaveKw",
      "refrigeratorKw",
      "netHousePowerUsageKw",
      "garageReceptaclesLightsKw",
      "garageReceptaclesKw",
      "shedReceptaclesKw",
      "shedLightsKw",
      "garagePVKw",
      "guestHouseLivingRoomKw",
      "masterBedroomKw",
      "heatCirculatorPumpsKw",
      "domesticHotWaterReserveKw",
      "masterBathroomKw",
      "kitchenIslandKw",
      "radiantHeatReserveTankKw",
      "basementReceptaclesKw",
      "dryerKw",
      "kitchenLightingKw",
      "guestHouseDiningRoomReceptKw",
      "porchVerandaLightingKw",
    ],
  },
  {
    relatedRole: "Tenant",
    home: "homeE",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "kitchenOutletEspressoKw",
      "hotWaterHeaterKw",
      "diningRoomKw",
      "fridgeEntLightsKw",
      "clothesWashingMachineKw",
      "dishwasherKw",
      "secondFloorBedroomKw",
      "masterNEbedroomBathKw",
      "elecHeatKw",
      "furnaceKw",
      "laundLivingRHallLightsKw",
      "gridKw",
      "kitchenKw",
      "firstFloorBedroomKw",
      "ovenKw",
      "dryerKw",
      "basementDehumidifierKw",
      "basementFamilyRoomKw",
      "elecHeatBedWBathNKw",
    ],
  },
  {
    relatedRole: "Tenant",
    home: "homeF",
    fields: [
      "dateTime",
      "usedKw",
      "generateKw",
      "waterHeaterKw",
      "solarKw",
      "refrigeratorKw",
      "microwaveKw",
      "furnaceKw",
      "waterHeater3Kw",
      "waterHeater2Kw",
      "waterHeater1Kw",
      "masterBdrmKw",
      "frontBdrmKw",
      "kitStoveWallKw",
      "dishwasherDisposalKw",
      "kitSinkWallKw",
      "familyRmKw",
      "kitHalfBathFoyerKw",
      "washingMachineKw",
      "guestBdrmSmkDetKw",
      "dryerKw",
      "basementKw",
      "phaseBKw",
      "phaseAKw",
      "netMeterKw",
      "voltKw",
      "garageEKw",
      "garageWKw",
    ],
  },
];

const CleaningCompanyEmployee = [
  {
    relatedRole: "CleaningCompanyEmployee",
    home: "homeA",
    fields: [
      "dateTime",
      "cellarOutletsKw",
      "washingMachineKw",
      "disposalDishwasherKw",
      "kitchenLightsKw",
      "bedroomLightsKw",
      "masterLightsKw",
      "dryerKw",
      "kitchenDenLightsKw",
      "masterBedBathLightsKw",
      "denOutdoorLightsKw",
      "rearBasementLightsKw",
      "dishwasherDisposalSinkLightKw",
      "officeLightsKw",
    ],
    accessTimePermission: {
      from: "9",
      to: "10"
    },
  },
  {
    relatedRole: "CleaningCompanyEmployee",
    home: "homeB",
    fields: [
      "dateTime",
      "cellarLightsKw",
      "washerKw",
      "firstFloorLightsKw",
      "dryerEgaugeKw",
      "tubWhirpoolKw",
      "dishwasherKw",
      "fridgeKw",
      "guestBedroomMediaRoomKw",
      "mBedKBedLightsMasterBathkw",
      "livingRoomKitchenLightsKw",
    ],
    accessTimePermission: {
      from: "9",
      to: "10"
    },
  },
  {
    relatedRole: "CleaningCompanyEmployee",
    home: "homeC",
    fields: [
      "dateTime",
      "dishwasherKw",
      "homeOfficeKw",
      "livingRoomKw",
      "washerDrierKw",
    ],
    accessTimePermission: {
      from: "10",
      to: "11"
    },
  },
  {
    relatedRole: "CleaningCompanyEmployee",
    home: "homeD",
    fields: [
      "dateTime",
      "secondFloorBathroomKw",
      "washingMachineKw",
      "basementHallLightingKw",
      "guestHouseBathroomKw",
      "guestHouseBedroomKw",
      "guestHouseKitchenKw",
      "shedLightsKw",
      "guestHouseLivingRoomKw",
      "masterBedroomKw",
      "masterBathroomKw",
      "kitchenIslandKw",
      "dryerKw",
      "kitchenLightingKw",
    ],
    accessTimePermission: {
      from: "9",
      to: "10"
    },
  },
  {
    relatedRole: "CleaningCompanyEmployee",
    home: "homeE",
    fields: [
      "dateTime",
      "diningRoomKw",
      "fridgeEntLightsKw",
      "clothesWashingMachineKw",
      "dishwasherKw",
      "secondFloorBedroomKw",
      "masterNEbedroomBathKw",
      "laundLivingRHallLightsKw",
      "kitchenKw",
      "firstFloorBedroomKw",
      "dryerKw",
      "basementFamilyRoomKw",
    ],
    accessTimePermission: {
      from: "10",
      to: "11"
    },
  },
  {
    relatedRole: "CleaningCompanyEmployee",
    home: "homeF",
    fields: [
      "dateTime",
      "masterBdrmKw",
      "frontBdrmKw",
      "dishwasherDisposalKw",
      "kitHalfBathFoyerKw",
      "washingMachineKw",
      "guestBdrmSmkDetKw",
      "dryerKw",
      "basementKw",
    ],
    accessTimePermission: {
      from: "11",
      to: "12"
    },
  },
];

export default [
  ResidenceOwner,
  HomeOwner,
  UnderageResident,
  Tenant,
  CleaningCompanyEmployee,
];
