apiVersion: v1
kind: ConfigMap
metadata:
  name: datadb-configmap
  namespace: master-thesis
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
  ensure-users.js: |
    const rootUser = cat('/etc/k8-mounts/admin/MONGO_ROOT_USERNAME');
    const rootPass = cat('/etc/k8-mounts/admin/MONGO_ROOT_PASSWORD');
    const adminDb = db.getSiblingDB('admin');
    adminDb.auth(rootUser, rootPass);
    
    const masterDbStr = 'master';
    const masterDb = db.getSiblingDB(masterDbStr);
    const masterUser = cat('/etc/k8-mounts/MONGO_MASTER_USERNAME');
    const masterPass = cat('/etc/k8-mounts/MONGO_MASTER_PASSWORD');
    masterDb.createUser({user: masterUser, pwd: masterPass, roles: [{role: "readWrite", db: masterDbStr}]})
