apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: master-thesis
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
  ensure-users.js: |
    const rootUser = cat('/etc/k8-mounts/admin/MONGO_ROOT_USERNAME');
    const rootPass = cat('/etc/k8-mounts/admin/MONGO_ROOT_PASSWORD');
    const adminDb = db.getSiblingDB('admin');
    adminDb.auth(rootUser, rootPass);
    
    const masterDbStr = 'master';
    const masterDb = db.getSiblingDB(masterDbStr);
    const masterUser = cat('/etc/k8-mounts/MONGO_MASTER_USERNAME');
    const masterPass = cat('/etc/k8-mounts/MONGO_MASTER_PASSWORD');
    masterDb.createUser({user: masterUser, pwd: masterPass, roles: [{role: "readWrite", db: masterDbStr}]})
  load-files.sh: |
    DB_MASTER="master"
    COLLECTION="measurements"
    HOME_OWNER_USER=$(cat /etc/k8-mounts/MONGO_MASTER_USERNAME)
    HOME_OWNER_PASS=$(cat /etc/k8-mounts/MONGO_MASTER_PASSWORD)
    DATA_FILE="dataset/HomeA/2014/HomeA-meter2_2014.json" 
    mongoimport -u $HOME_OWNER_USER -p $HOME_OWNER_PASS --db $DB_MASTER --collection $COLLECTION --file $DATA_FILE --jsonArray


