apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: master-thesis
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
  ensure-users.js: |
    const rootUser = cat('/etc/k8-mounts/admin/MONGO_ROOT_USERNAME');
    const rootPass = cat('/etc/k8-mounts/admin/MONGO_ROOT_PASSWORD');
    const adminDb = db.getSiblingDB('admin');
    adminDb.auth(rootUser, rootPass);
    
    const masterDbStr = 'master';
    const masterDb = db.getSiblingDB(masterDbStr);
    const masterUser = cat('/etc/k8-mounts/MONGO_MASTER_USERNAME');
    const masterPass = cat('/etc/k8-mounts/MONGO_MASTER_PASSWORD');
    masterDb.createUser({user: masterUser, pwd: masterPass, roles: [{role: "readWrite", db: masterDbStr}]})
  
  load-files-homeA.sh: |
    DB_MASTER="master"
    COLLECTION="homeA"
    MONGO_MASTER_USERNAME=$(cat /etc/k8-mounts/MONGO_MASTER_USERNAME)
    MONGO_MASTER_PASSWORD=$(cat /etc/k8-mounts/MONGO_MASTER_PASSWORD)
    DATA_FILE_2014="/dataset/HomeA/2014/"
    DATA_FILE_2015="/dataset/HomeA/2015/"
    DATA_FILE_2016="/dataset/HomeA/2016/"

    cd $DATA_FILE_2014
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
  
  load-files-homeB.sh: |
    DB_MASTER="master"
    COLLECTION="homeB"
    MONGO_MASTER_USERNAME=$(cat /etc/k8-mounts/MONGO_MASTER_USERNAME)
    MONGO_MASTER_PASSWORD=$(cat /etc/k8-mounts/MONGO_MASTER_PASSWORD)
    DATA_FILE_2014="/dataset/HomeB/2014/"
    DATA_FILE_2015="/dataset/HomeB/2015/"
    DATA_FILE_2016="/dataset/HomeB/2016/"

    cd $DATA_FILE_2014
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done

  load-files-homeC.sh: |
    DB_MASTER="master"
    COLLECTION="homeC"
    MONGO_MASTER_USERNAME=$(cat /etc/k8-mounts/MONGO_MASTER_USERNAME)
    MONGO_MASTER_PASSWORD=$(cat /etc/k8-mounts/MONGO_MASTER_PASSWORD)
    DATA_FILE_2014="/dataset/HomeC/2014/"
    DATA_FILE_2015="/dataset/HomeC/2015/"
    DATA_FILE_2016="/dataset/HomeC/2016/"

    cd $DATA_FILE_2014
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done

  load-files-homeD.sh: |
    DB_MASTER="master"
    COLLECTION="homeD"
    MONGO_MASTER_USERNAME=$(cat /etc/k8-mounts/MONGO_MASTER_USERNAME)
    MONGO_MASTER_PASSWORD=$(cat /etc/k8-mounts/MONGO_MASTER_PASSWORD)
    DATA_FILE_2015="/dataset/HomeD/2015/"
    DATA_FILE_2016="/dataset/HomeD/2016/"

    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done


  load-files-homeE.sh: |
    DB_MASTER="master"
    COLLECTION="homeE"
    MONGO_MASTER_USERNAME=$(cat /etc/k8-mounts/MONGO_MASTER_USERNAME)
    MONGO_MASTER_PASSWORD=$(cat /etc/k8-mounts/MONGO_MASTER_PASSWORD)
    DATA_FILE_2016="/dataset/HomeE/2016/"

    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done


  load-files-homeF.sh: |
    DB_MASTER="master"
    COLLECTION="homeF"
    MONGO_MASTER_USERNAME=$(cat /etc/k8-mounts/MONGO_MASTER_USERNAME)
    MONGO_MASTER_PASSWORD=$(cat /etc/k8-mounts/MONGO_MASTER_PASSWORD)
    DATA_FILE_2014="/dataset/HomeF/2014/"
    DATA_FILE_2015="/dataset/HomeF/2015/"
    DATA_FILE_2016="/dataset/HomeF/2016/"

    cd $DATA_FILE_2014
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done


  load-files-all.sh: |
    DB_MASTER="master"
    MONGO_MASTER_USERNAME=$(cat /etc/k8-mounts/MONGO_MASTER_USERNAME)
    MONGO_MASTER_PASSWORD=$(cat /etc/k8-mounts/MONGO_MASTER_PASSWORD)
    
    COLLECTION="homeA"
    DATA_FILE_2014="/dataset/HomeA/2014/"
    DATA_FILE_2015="/dataset/HomeA/2015/"
    DATA_FILE_2016="/dataset/HomeA/2016/"
    cd $DATA_FILE_2014
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
  

    COLLECTION="homeB"
    DATA_FILE_2014="/dataset/HomeB/2014/"
    DATA_FILE_2015="/dataset/HomeB/2015/"
    DATA_FILE_2016="/dataset/HomeB/2016/"
    cd $DATA_FILE_2014
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done


    COLLECTION="homeC"
    DATA_FILE_2014="/dataset/HomeC/2014/"
    DATA_FILE_2015="/dataset/HomeC/2015/"
    DATA_FILE_2016="/dataset/HomeC/2016/"
    cd $DATA_FILE_2014
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done


    COLLECTION="homeD"
    DATA_FILE_2015="/dataset/HomeD/2015/"
    DATA_FILE_2016="/dataset/HomeD/2016/"
    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done


    COLLECTION="homeE"
    DATA_FILE_2016="/dataset/HomeE/2016/"
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done

    COLLECTION="homeF"
    DATA_FILE_2014="/dataset/HomeF/2014/"
    DATA_FILE_2015="/dataset/HomeF/2015/"
    DATA_FILE_2016="/dataset/HomeF/2016/"
    cd $DATA_FILE_2014
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2015
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
    cd $DATA_FILE_2016
    ls -1 *.json | while read jsonfile; do mongoimport -u $MONGO_MASTER_USERNAME -p $MONGO_MASTER_PASSWORD --db $DB_MASTER --collection $COLLECTION --file $jsonfile --jsonArray; done
