apiVersion: v1
kind: Service
metadata:
  namespace: master-thesis
  name: node-server-service
spec:
  selector:
    app: node-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110