apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
    namespace: master-thesis
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storageclass
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: size
          operator: In
          values:
            - large

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataset
  namespace: master-thesis
  labels:
    type: local
spec:
  storageClassName: hostpath
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/dataset
  persistentVolumeReclaimPolicy: Retain