apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-statefulset
  namespace: master-thesis
spec:
  serviceName: user-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: user-statefulset
    spec:
      containers:
        - name: user-statefulset
          image: mongo:4.0.8
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/k8-mounts/admin/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/k8-mounts/admin/MONGO_ROOT_PASSWORD
            - name: MONGO_MASTER_USERNAME_FILE
              value: /etc/k8-mounts/admin/MONGO_MASTER_USERNAME
            - name: MONGO_MASTER_PASSWORD_FILE
              value: /etc/k8-mounts/admin/MONGO_MASTER_PASSWORD
          volumeMounts:
            - name: k8-mounts
              mountPath: /etc/k8-mounts
              readOnly: true
            - name: mongodb-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: mongodb-configmap
              mountPath: /config
              readOnly: true
            - name: users-data #TODO: creare!
              mountPath: /data/db
      nodeSelector:
        size: large
      volumes:
        - name: k8-mounts
          secret:
            secretName: mongodb-secret
            items:
              - key: MONGO_ROOT_USERNAME
                path: admin/MONGO_ROOT_USERNAME
                mode: 0444
              - key: MONGO_ROOT_PASSWORD
                path: admin/MONGO_ROOT_PASSWORD
                mode: 0444
              - key: MONGO_MASTER_USERNAME
                path: MONGO_MASTER_USERNAME
                mode: 0444
              - key: MONGO_MASTER_PASSWORD
                path: MONGO_MASTER_PASSWORD
                mode: 0444
        - name: mongodb-scripts
          configMap:
            name: mongodb-configmap
            items:
              - key: ensure-users.js
                path: ensure-users.js
        - name: mongodb-configmap
          configMap:
            name: mongodb-configmap
            items:
              - key: mongo.conf
                path: mongo.conf
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: users-pvc
