apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: master_thesis
resources:
  - configMap.yaml
  - persistent_volume_claim.yaml.yaml
  - persistent_volume.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml
  - storage_class.yaml