apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
    namespace: master-thesis
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storageclass
  local:
    path: /mnt/data
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: size
  #         operator: In
  #         values:
  #           - large